name: Update README

on:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script to update README
      run: |
        python make_readme.py --token "${{ secrets.GH_TOKEN }}" > README.md.trial

    - name: Compare README.md.trial with README.md
      id: compare_readme
      run: |
        set +e
        cmp -s README.md README.md.trial
        echo "exitcode=$?" >> "$GITHUB_OUTPUT"

    - name: Echo compare result
      run: echo "${{steps.compare_readme.outputs.exitcode}}"

    - name: Rename README.md.trial to README.md
      if: steps.compare_readme.outputs.exitcode != 0
      run: mv README.md.trial README.md

    - name: Commit changes to README
      if: steps.compare_readme.outputs.exitcode != 0
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git add README.md
        git commit -m "[Github Action] Update README.md" || true
        git push

